#!/bin/bash
__basic_dependencies(){
	sudo apt update

	sudo apt install apt-transport-https -y
	sudo apt install curl -y
	sudo apt install ca-certificates -y
	sudo apt install software-properties-common -y
	sudo apt install snapd -y
	sudo apt install gnupg -y

	sudo apt update
}

__basic_dependencies