#!/bin/bash

__folders() {
	# echo 'Creating needed folders'
	# mkdir -p ~/Documentos/pessoais
	mkdir -p ~/Documentos/maplink
	mkdir -p ~/.local/bin
	mkdir -p ~/.local/files
	mkdir -p ~/.vpn
	mkdir -p ~/.local/share/gnome-shell/extensions
	mkdir -p ~/.intellij
	mkdir -p ~/.oh-my-posh
}

__commands() {
	# echo 'Addind ~/.local/bin to PATH'
	BIN='/home/felipe/.local/bin'
	# ln -s $HOME/Documentos/pessoais/configuration/files/comandos $HOME/.local/bin
	# export PATH="$BIN:$PATH"
	ln -s $HOME/Documentos/pessoais/configuration/files/comandos/vpn $HOME/.local/bin/vpn
	ln -s $HOME/Documentos/pessoais/configuration/files/comandos/k8s $HOME/.local/bin/k8s
	ln -s $HOME/Documentos/pessoais/configuration/files/comandos/maplink $HOME/.local/bin/maplink
	# ln -s $HOME/Documentos/pessoais/configuration/files/comandos/backup $BIN/backup
	# ln -s $HOME/Documentos/pessoais/configuration/files/comandos/commit $BIN/commit
	# ln -s $HOME/Documentos/pessoais/configuration/files/comandos/vpnc /home/felipe/.local/bin/vpnc
	# ln -s $HOME/Documentos/pessoais/configuration/files/comandos/vpnd /home/felipe/.local/bin/vpnd
	# ln -s $HOME/Documentos/pessoais/configuration/files/comandos/vpns /home/felipe/.local/bin/vpns
}

__aliases() {
	# echo 'Creating symbolical link to bash_aliases...'
	# ln -s $HOME/Documentos/pessoais/configuration/files/bash_aliases $HOME/.bash_aliases
	ln -s $HOME/Documentos/pessoais/configuration/files/bash_aliases $HOME/.aliases
}

__shortcuts() {
	# echo 'Creating shortcut for notes in menu...'
	# ln -s $ORIGEM $DESTINO
	# ln -s $HOME/Documentos/pessoais/configuration/files/atalhos/notas.desktop $HOME/.local/share/applications/notas.desktop
	ln -s $HOME/Documentos/pessoais/configuration/files/atalhos/intellij.desktop $HOME/.local/share/applications/intellij.desktop
	ln -s $HOME/Documentos/pessoais/configuration/files/atalhos/postman.desktop $HOME/.local/share/applications/postman.desktop
}

__maplink_notes() {
	ln -s $HOME/Documentos/maplink/anotacoes $HOME/Documentos/pessoais/maplink
	cp -R /media/$USER/PENDRIVE/maplink/anotacoes ~/Documentos/maplink/
}

# __clone_setup_environment_files() {
# 	# echo 'Cloning repository with basic files for configuration...'
# 	curl -L https://github.com/felipemendes1994/setup-environment-files/archive/refs/heads/master.zip -o ~/Downloads/setup-environment-files.zip
# 	unzip ~/Downloads/setup-environment-files.zip
# 	mv -R ~/Downloads/setup-environment-files ~/Documentos/pessoais
# 	trash ~/Downloads/setup-environment-files.zip
# }

__setup_brave(){
	echo 'Configuring Brave'
	echo 'Copying extensions to Brave folder...'
	rm -rf ~/.config/BraveSoftware/Brave-Browser/Default/Extensions
	cp -r ~/Documentos/pessoais/configuration/files/brave-browser/Extensions ~/.config/BraveSoftware/Brave-Browser/Default


	echo 'Copying Brave preferences to Brave folder...'
	rm -rf ~/.config/BraveSoftware/Brave-Browser/Default/Preferences
	cp -r ~/Documentos/pessoais/configuration/files/brave-browser/Preferences ~/.config/BraveSoftware/Brave-Browser/Default


	echo 'Copying Brave Bookmarks to Brave folder...'
	rm -rf ~/.config/BraveSoftware/Brave-Browser/Default/Bookmarks
	cp -r ~/Documentos/pessoais/configuration/files/brave-browser/Bookmarks ~/.config/BraveSoftware/Brave-Browser/Default


	echo 'Copying Brave History to Brave folder...'
	rm -rf ~/.config/BraveSoftware/Brave-Browser/Default/History
	cp -r ~/Documentos/pessoais/configuration/files/brave-browser/History ~/.config/BraveSoftware/Brave-Browser/Default

	# Talvez precise adicionar aqui os grupos de guias
}

__gnome_extensions() {
	cd ~/.local/share/gnome-shell/extensions/

    echo "Need adjustments"
	# https://manpages.ubuntu.com/manpages/focal/man1/gnome-extensions.1.html
	# gnome-extensions --help

	# sound-output-device-chooser@kgshank.net
	# status-area-horizontal-spacing@mathematical.coffee.gmail.com
	# gTile@vibou
	# vpn-indicator@howdoicomputer.fastmail.com
	# blur-my-shell@aunetx
	# dash-to-dock@micxgx.gmail.com
}

__gnome_configurations(){
	dconf load / < ~/home/felipe/Documentos/pessoais/configuration/files/user.conf
	# Restaura todas as configuracoes do usuario do gnome shell
	# dconf load / < full-backup #trocar full-backup pelo local do arquivo
}

__ohmyposh() {
	oh-my-posh font install meslo
}

__vpn(){
	# echo "Setting up vpn..."
	cp /media/$USER/PENDRIVE/config/vpn/default-vpn.ovpn ~/.vpn
}

__setup_sshkeys_on_git_projects(){
	cd $HOME/Documentos/pessoais/configuration/files; git config core.sshCommand "ssh -i ~/.ssh/github_rsa"
	cd $HOME/Documentos/pessoais/configuration/scripts; git config core.sshCommand "ssh -i ~/.ssh/github_rsa"
}

__ssh(){
	echo "Setting up ssh keys..."
	cp /media/$USER/PENDRIVE/config/ssh/* $HOME/.ssh
	chmod 600 $HOME/.ssh/*
	chmod 644 $HOME/.ssh/*.pub
	ssh-add $HOME/.ssh/id_rsa $HOME/.ssh/github_rsa
	# __setup_sshkeys_on_git_projects
}

__musics(){
	cp -R /media/$USER/PENDRIVE/files/music/* ~/Música
}

__images(){
	cp -R /media/$USER/PENDRIVE/files/images/* ~/Imagens
}

__zsh(){
	# chsh -s /bin/zsh
	cd ~/.oh-my-zsh/custom/plugins
	git clone git@github.com:zsh-users/zsh-autosuggestions.git
	git clone git@github.com:zsh-users/zsh-syntax-highlighting.git
	# Precisa instalar os plugins zsh-autosuggestions e zsh-syntax-highlighting
}

__logs(){
	sudo mkdir /var/log/backups
	sudo touch /var/log/backups/gdrive-backup.log
	sudo touch /var/log/backups/backup.log
	sudo chown -R felipe /var/log/backups
	sudo chmod 750 /var/log/backups/gdrive-backup.log /var/log/backups/backup.log
}

__keepassxc(){
	cp /media/felipe/PENDRIVE/config/credentials.kdbx ~/Documentos/pessoais/configuration/files
}

__gcloud_sdk(){
	gcloud auth login
	gcloud init
	gcloud container clusters get-credentials mlp-cluster
	gcloud container clusters get-credentials maplink-cluster-01
}

__help(){
	echo "Personal configuration script"
	echo ""
	echo "folders			Create needed folders"
	echo "commands			Create symbolical link to personal commands"
	echo "aliases			Create symbolical link to bash_aliases file"
	echo "shortcuts			Create symbolical link to personal shortcuts"
	# echo "sef				Download personal environment files from github"
	echo "brave				Replace brave files with local ones"
	echo "extensions		Install needed gnome-shell-extensions"
	# echo "config			Import gnome-shell configurations to SO"
	echo "myposh			Setup oh my posh fonts"
	echo "vpn				Setup vpn"
	echo "ssh				Setup ssh keys"
	echo "musics			Copy musics to pc"
	echo "images			Copy Images to pc"
	echo "maplink-notes		Copy Maplink notes to pc"
	echo "zsh				Set ZSH as default shell"
	echo "logs				Create folder and files for backup logs"
	echo "all				Run all options mentioned above"
}

__all() {
	# __folders
	__commands
	__aliases
	__shortcuts
	# __clone_setup_environment_files
	__setup_brave
	__gnome_extensions
	__gnome_configurations
	__ohmyposh
	__vpn
	__ssh
	__musics
	__images
	__zsh
	__logs
	__maplink_notes
}

case $1 in
	folders) __folders;;
	commands) __commands;;
	aliases) __aliases;;
	shortcuts) __shortcuts;;
	# sef) __clone_setup_environment_files;;
	brave) __setup_brave;;
	extensions) __gnome_extensions;;
	config) __gnome_configurations;;
	myposh) __ohmyposh;;
	vpn) __vpn;;
	ssh) __ssh;;
	musics) __musics;;
	images) __images;;
	maplink-notes) __maplink_notes;;
	zsh) __zsh;;
	logs) __logs;;
	keepassxc) __keepassxc;;
	all) all;;
	help | -h | *) __help;;
esac 

# 	echo 'https://extensions.gnome.org/extension/307/dash-to-dock/'
# 	echo 'https://extensions.gnome.org/extension/1465/desktop-icons/'
# 	echo 'https://extensions.gnome.org/extension/906/sound-output-device-chooser/'
# 	echo 'https://extensions.gnome.org/extension/355/status-area-horizontal-spacing/'
# 	echo 'https://extensions.gnome.org/extension/120/system-monitor/'