#!/bin/bash
__terminator(){
	sudo apt install terminator -y
}

__vim(){
	sudo apt install vim -y
}

__git(){
	sudo apt install git -y
}

__vscode(){
	sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
	curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
	sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
	sudo apt update
	sudo apt install code -y
}

__dbeaver(){
	echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list
	wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -
	sudo apt update
	sudo apt-get install dbeaver-ce -y
}

__npm(){
	sudo apt install npm -y
}

__nvm(){
	# https://linuxize.com/post/how-to-install-node-js-on-ubuntu-18.04/
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
	export NVM_DIR="$HOME/.nvm"
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
	[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
}

__maven(){
	sudo apt install maven -y
}

__yarn(){
	curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
	echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
	sudo apt update 
	sudo apt install yarn -y
}

__docker(){
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
	sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
	sudo apt update
	apt-cache policy docker-ce
	sudo apt install docker-ce -y

	sudo usermod -aG docker ${USER}
}

__docker_compose(){
	sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
	sudo chmod +x /usr/local/bin/docker-compose
}

__nodejs(){
	sudo apt install nodejs
}

__quarkus_cli(){
	curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/
	curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio
	jbang app install --fresh --force quarkus@quarkusio

	source <(quarkus completion)
}

__all(){
	__terminator
	__vim
	__git
	__vscode
	__dbeaver
	__npm
	__nvm
	__maven
	__yarn
	__docker
	__docker_compose
	__nodejs
	__quarkus_cli
}

case $1 in
	terminator) __terminator;;
	vim) __vim;;
	git) __git;;
	vscode) __vscode;;
	dbeaver) __dbeaver;;
	npm) __npm;;
	nvm) __nvm;;
	maven) __maven;;
	yarn) __yarn;;
	docker) __docker;;
	docker-compose) __docker_compose;;
	node) __nodejs;;
	quarkus) __quarkus_cli;;
	all) __all;;
esac