#!/bin/bash

install_browsers(){
	# __google_chrome
	__brave_browser
}

install_development_tools(){
	__terminator
	__vim
	__git
	__vscode
	__dbeaver
	__npm
	__nvm
	__maven
	__yarn
	__docker
	__docker_compose
	# __nodejs
}


install_java_versions(){

}



install_tools(){
	# __discord
	__slack
	# __teams
	__spotify
	__libre_office
	__whatsapp
	__notion
	__trello
	__postman
}

_wait_and_clear(){
	read -p '' -n1 -s
	clear
}


__final_message(){
	echo 'There is some remaining configuration you must do manually...'
	echo 'Press any key to finalize this script...'
	_wait_and_clear
}

_open_brave(){
	brave-browser
}

personal_setup(){
	__add_user_in_sudoers_file

	__papyrus_icons

	__create_personal_dir
	__create_personal_workspaces	

	# __create_ssh_key
	__clone_personal_files_repository
	__download_files_from_drive #maybe all these file should be inside the repository

	__create_local_bin_dir_and_add_to_path

	__create_symbolical_link_for_bash_aliases
	__create_shortcut_to_notes

	__add_brave_extensions
	__add_brave_preferences
	
	__set_git_branch_on_terminal

	__set_gnome_extensions

	__final_message
}

remove_unnecessary_packages(){
	sudo apt autoremove -y
}

setup_only(){
	# echo 'To run setup successfully, the OS must be restarted first... '

	echo 'Now the personal configuration is going to start...'
	echo 'Press any key to proceed...'
	_wait_and_clear
	read -p '' -n1 -s
	clear
	personal_setup
	remove_unnecessary_packages
}

full_installation(){
	basic_dependencies
	browsers
	development_tools
	java_versions
	tools
	_open_brave
	# echo 'Now you must restart the OS to finish the configuration'
	setup_only
	# Precisa reiniciar o SO
}
	
if [ "$1" ]; then
	if [ "$1" = "--install-apps" ]; then 
		full_installation
	fi

	if [ "$1" = "--setup" ]; then
		personal_setup
		remove_unnecessary_packages
	fi
else
	echo 'You must say which kind of installation you want to make...'
	echo 'provide the arg --install_apps for a full installation or --setup only for setup'
fi