#!/bin/bash

__java8(){
	sudo apt install openjdk-8-jdk -y
}

__java11(){
	sudo apt install openjdk-11-jdk -y
}

__java13(){
	sudo apt install openjdk-13-jdk -y
}

__java16(){
	sudo apt install openjdk-16-jdk -y
}

__all(){
	__java8
	__java11
	# __java13
	# __java16
}

case $1 in
	java8) __java8;;
	java11) __java11;;
	# java13) __java13;;
	# java16) __java16;;
	all) __all;;
	*) echo "Bad commands execution. No actions taken."; exit 1;;
esac