#!/bin/bash

__java8(){
	sudo apt install openjdk-8-jdk -y
}

__java11(){
	sudo apt install openjdk-11-jdk -y
}

__java17(){
	sudo apt install openjdk-17-jdk -y
}

__java21(){
	sudo apt install openjdk-21-jdk -y
}

__all(){
	__java8
	__java11
	__java21
	# __java13
	# __java16
}

case $1 in
	java8) __java8;;
	java11) __java11;;
	java17) __java17;;
	java21) __java21;;
	all) __all;;
	*) echo "Bad commands execution. No actions taken."; exit 1;;
esac