#!/bin/bash
__postman(){
	# sudo snap install postman
	wget https://dl.pstmn.io/download/latest/linux64 -O /tmp/postman-linux-x64.tar.gz
	cd /tmp
	tar -zxvf ./postman-linux-x64.tar.gz
	sudo mv ./Postman /opt
	sudo ln -s /opt/Postman/Postman /usr/local/bin/postman
}

__discord(){
	sudo snap install discord
}

__slack(){
	# sudo snap install slack
	cd /tmp; wget https://downloads.slack-edge.com/releases/linux/4.28.184/prod/x64/slack-desktop-4.28.184-amd64.deb
	sudo dpkg -i /tmp/slack-desktop-4.28.184-amd64.deb
}

__teams(){
	sudo snap install teams
}

__spotify(){
	# curl -sS https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg
	curl -sS https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg
	echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
	sudo apt-get update && sudo apt-get install spotify-client -y
}

__libre_office(){
	sudo apt install libreoffice-gnome libreoffice -y
}

__whatsapp(){
	sudo snap install whatsapp-app
}

__notion(){
	sudo apt install notion -y
}

__trello(){
	sudo snap install trello-desktop
}

__trash(){
	sudo apt install trash-cli -y
}

__gnome_tweaks(){
	sudo apt install gnome-tweaks -y
}

__gnome_extensions(){
	sudo apt install gnome-shell-extensions gnome-shell-extension-manager -y
}

__ohmyposh(){
	sudo wget https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64 -O /usr/local/bin/oh-my-posh
	sudo chmod +x /usr/local/bin/oh-my-posh
}

__vpn(){
	curl -fsSL https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub | gpg --dearmor | sudo tee /usr/share/keyrings/openvpn-repo-pkg-keyring.gpg
	DIST=$(lsb_release -c | cut -f2)
	echo "deb [signed-by=/usr/share/keyrings/openvpn-repo-pkg-keyring.gpg] https://swupdate.openvpn.net/community/openvpn3/repos $DIST main" | sudo tee -a /etc/apt/sources.list.d/openvpn3.list
	sudo apt update
	sudo apt install openvpn3
}

__zsh(){
	sudo apt install zsh -y
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
}

__keepassxc(){
	sudo apt install keepassxc -y
}

__vlc(){
	sudo apt install vlc
}

__syncthing(){
	echo "deb https://apt.syncthing.net/ syncthing stable" | sudo tee /etc/apt/sources.list.d/syncthing.list
	curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
	sudo apt update
	sudo apt install syncthing
	#https://www.linuxfordevices.com/tutorials/ubuntu/syncthing-install-and-setup
}

__hidamari(){
	flatpak install --user https://flathub.org/repo/appstream/io.github.jeffshee.Hidamari.flatpakref
}

__gnome_boxes(){
	flatpak install flathub org.gnome.boxes
}

__flameshot() {
	sudo apt install flameshot
}

__help(){
	echo "Persona tools script"
	echo ""
	echo "postman			Install postman"
	echo "discord			Install discord"
	echo "slack				Install slack"
	echo "teams				Install teams"
	echo "spotify			Install spotify"
	echo "libreoffice		Install libreoffice"
	echo "whatsapp			Install whatsapp"
	echo "notion			Install notion"
	echo "trello			Install trello"
	echo "tweaks			Install Gnome Tweaks"
	echo "extensions		Install Gnome Extensions"
	echo "ohmyposh			Install Oh My Posh"
	echo "vpn				Install Openvpn3"
	echo "vlc               Install VLC Player"
	echo "syncthing         Install SyncThing"
	echo "zsh				Install Zshell"
	echo "zsh				Install KeePassXC"
	echo "hidamari			Install Hidamari"
	echo "Gnome Boxes		Install Gnome Boxes"
	echo "all				Install all tools mentioned above"
}

__all(){
	__postman
	# __discord
	__slack
	# __teams
	__spotify
	__libre_office
	# __whatsapp
	__notion
	__trello
	__trash
	__gnome_tweaks
	__gnome_extensions
	__ohmyposh
	__vpn
	__vlc
	__zsh
	__keepassxc
	__syncthing
	__flameshot
	__hidamari
	__gnome_boxes
}

case $1 in
	postman) __postman;;
	discord) __discord;;
	slack) __slack;;
	teams) __teams;;
	spotify) __spotify;;
	libreoffice) __libre_office;;
	whatsapp) __whatsapp;;
	notion) __notion;;
	trello) __trello;;
	trash) __trash;;
	tweaks) __gnome_tweaks;;
	extensions) __gnome_extensions;;
	ohmyposh) __ohmyposh;;
	vpn) __vpn;;
	vlc) __vlc;;
	zsh) __zsh;;
	keepassxc) __keepassxc;;
	syncthing) __syncthing;;
	flameshot) __flameshot;;
	hidamari) __hidamari;;
	gnome_boxes) __gnome_boxes;;
	all) __all;;
	help | -h | *) __help;;
esac