#!/bin/bash
__postman(){
	sudo snap install postman
}

__discord(){
	sudo snap install discord
}

__slack(){
	sudo snap install slack
}

__teams(){
	sudo snap install teams
}

__spotify(){
	sudo snap install spotify
}

__libre_office(){
	sudo apt install libreoffice-gnome libreoffice -y
}

__whatsapp(){
	sudo snap install whatsapp-app
}

__notion(){
	sudo snap install notion-snap
}

__trello(){
	sudo snap install trello-desktop
}

__trash(){
	sudo apt install trash-cli -y
}

__gnome_tweaks(){
	sudo apt install gnome-tweaks -y
}

__gnome_extensions(){
	sudo apt install gnome-shell-extensions -y
}

__ohmyposh(){
	sudo wget https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64 -O /usr/local/bin/oh-my-posh
	sudo chmod +x /usr/local/bin/oh-my-posh
}

__vpn(){
	curl -fsSL https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub | gpg --dearmor | sudo tee /usr/share/keyrings/openvpn-repo-pkg-keyring.gpg
	echo "deb [signed-by=/usr/share/keyrings/openvpn-repo-pkg-keyring.gpg] https://swupdate.openvpn.net/community/openvpn3/repos $(lsb_release -c) main" | sudo tee -a /etc/apt/sources.list.d/openvpn3.list
	sudo apt update
	sudo apt install openvpn3
}

__help(){
	echo "Persona tools script"
	echo ""
	echo "postman			Install postman"
	echo "discord			Install discord"
	echo "slack				Install slack"
	echo "teams				Install teams"
	echo "spotify			Install spotify"
	echo "libreoffice		Install libreoffice"
	echo "whatsapp			Install whatsapp"
	echo "notion			Install notion"
	echo "trello			Install trello"
	echo "tweaks			Install Gnome Tweaks"
	echo "extensions		Install Gnome Extensions"
	echo "ohmyposh			Install Oh My Posh"
	echo "vpn				Install Openvpn3"
	echo "all				Install all tools mentioned above"
}


__all(){
	__postman
	__discord
	__slack
	# __teams
	__spotify
	__libre_office
	# __whatsapp
	__notion
	__trello
	__trash
	__gnome_tweaks
	__gnome_extensions
	__ohmyposh
	__vpn
}

case $1 in
	postman) __postman;;
	discord) __discord;;
	slack) __slack;;
	teams) __teams;;
	spotify) __spotify;;
	libreoffice) __libre_office;;
	whatsapp) __whatsapp;;
	notion) __notion;;
	trello) __trello;;
	tweaks) __gnome_tweaks;;
	extensions) __gnome_extensions;;
	ohmyposh) __ohmyposh;;
	vpn) __vpn;;
	all) __all;;
	help | -h) __help;;
	*) echo "Bad commands execution. No actions taken."; exit 1;;
esac