#!/bin/bash
__postman(){
	sudo snap install postman
}

__discord(){
	sudo snap install discord
}

__slack(){
	sudo snap install slack
}

__teams(){
	sudo snap install teams
}

__spotify(){
	sudo snap install spotify
}

__libre_office(){
	sudo apt install libreoffice-gnome libreoffice -y
}

__whatsapp(){
	sudo snap install whatsapp-app
}

__notion(){
	sudo snap install notion-snap
}

__trello(){
	sudo snap install trello-desktop
}

__trash(){
	sudo apt install trash-cli
}

__gnome_tweaks(){
	sudo apt install gnome-tweaks -y
}


__all(){
	__postman
	__discord
	__slack
	# __teams
	__spotify
	__libre_office
	# __whatsapp
	__notion
	__trello
	__trash
	__gnome_tweaks
}

case $1 in
	postman) __postman;;
	discord) __discord;;
	slack) __slack;;
	teams) __teams;;
	spotify) __spotify;;
	libreoffice) __libre_office;;
	whatsapp) __whatsapp;;
	notion) __notion;;
	trello) __trello;;
	tweaks) __gnome_tweaks;;
	all) __all;;
esac